### PR TITLE
Update leaders.md

### PR DESCRIPTION
**Pull request by SPoint42**

### CODE REVIEW

**Comment by SPoint42** [comment]
@OWASPFoundation @hblankenship @mikemccamon @dawnaitken  more than 10 days for this pull request ? 
when could this be done to push code for the website . All the meeting and link from end 2019 are not online? There is a ticket to add it too, and no news 

A meeting have been done yesterday, and we don't have the capability since 1 month to push it on the new website....

**Comment by hblankenship** [comment]
Sebastien,

The intent for chapters is that the chapter leader(s) will manage any and
all updates/pull requests, not the Foundation staff.  Unfortunately, the
France chapter leader, Ludovic Petit, has not requested access to that
github repository.  In order to push your changes, It would be possible to
make you an admin on the chapter site if Ludovic indicates that he would
like you to be an admin as well.

Regards,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by SPoint42** [comment]
I did not know why ludovic as been made only chapter-leader for the France chapter. If you seen the changlog of the old wiki, you will see That I co-manage the chapter since 2006 with ludovic and update regularly last year the wiki. 

this is why I request my access to the github page and after adding the new board (Yann et didier)

thanks for the help

**Comment by SPoint42** [comment]
Need I do another new wufoo request ?

**Comment by hblankenship** [comment]
Hey, Sebastien,

Somehow, though Ludovic put you down as a chapter leader (I can see this on
the wiki) back in 2012, the system we use to verify it does not have you
listed.  I will make sure that gets updated.  I have given you permission
to the repository.

Cheers,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Pull request merged**
